name: carsus-data-repos-config

on: 
  workflow_dispatch: 
        
env:
  NBCONVERT_FLAGS: --execute --ExecutePreprocessor.timeout=600 --to html

defaults:
      run:
        shell: bash -l {0}

jobs:
  carsus-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: carsus/
                      
      - name: Cache carsus-data-cmfgen
        uses: actions/cache@v3
        with:
          path: cloned-repo-carsus-data-cmfgen
          key: ${{ runner.os }}-cache-${{ hashFiles('cloned-repo-carsus-data-cmfgen/**/*') }}
        id: cmfgen-cache
            
      - name: Clone carsus-data-cmfgen
        run: | 
          git clone https://github.com/tardis-sn/carsus-data-cmfgen cloned-repo-carsus-data-cmfgen
        if: steps.cmfgen-cache.outputs.cache-hit != 'true'

      - name: Cache Cloned carsus-data-kurucz
        uses: actions/cache@v3
        with:
          path: cloned-repo-carsus-data-kurucz
          key: ${{ runner.os }}-cache-${{ hashFiles('cloned-repo-carsus-data-kurucz/**/*') }}
        id: kurucz-cache

      - name: Clone Repo carsus-data-kurucz
        run: |
          git clone https://github.com/tardis-sn/carsus-data-kurucz cloned-repo-carsus-data-kurucz
        if: steps.kurucz-cache.outputs.cache-hit != 'true'

      - name: Cache Cloned carsus-data-nist
        uses: actions/cache@v3
        with:
          path: cloned-repo-carsus-data-nist
          key: ${{ runner.os }}-cache-${{ hashFiles('cloned-repo-carsus-data-nist/**/*') }}
        id: nist-cache

      - name: Clone Repo carsus-data-nist
        run: |
          git clone https://github.com/tardis-sn/carsus-data-nist cloned-repo-carsus-data-nist
        if: steps.nist-cache.outputs.cache-hit != 'true'
        
      - name: Setup carsus environment
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            environment-file: carsus/carsus_env3.yml
            activate-environment: carsus
            use-mamba: true

      - name: Install package
        run: pip install -e carsus/

      - name: Run notebooks
        run: |
          jupyter nbconvert ${{ env.NBCONVERT_FLAGS }} carsus/docs/tardis_atomdata_ref.ipynb
        env:
          CARSUS_REFDATA: ${{ github.workspace }}/carsus-refdata
        
      - name: Upload Atom Data
        uses: actions/upload-artifact@v3
        with:
          name: atom-data
          path: carsus/docs/kurucz_cd23_cmfgen_H_Si_I-II.h5
